---
.travis.yml:
  rubygems_api_key: "H7huqPGNv8bnpHl9IMiBCXOXod+LOGIpZWhABNHssw2do2c9vC1rO79Df/aLk09EITt7L2Xbs4AGfz5T70gL6iZZtQyWF1/NApSxSKUM7QZIW1p5VT7gMdfxR9Jk18XTJGHt7da1hoMPhLLOIrtF62lJyEDBjCTN+nBeZYhu6c8="
